travis:
  secure:
    BINSTAR_TOKEN: kCcL8kDyWzr4yQE1FQNfZyhffyzAezDbOYf4896chFO9GEkK50me2pzFX0Zf3QvWUuuqZx1GgKXZ5kqdOhLJJAyN777RGJGpwNtMtKwQbQXXc9mex8hR4SgyDOPoOs6guxW7U5k5Hp8neBypbdnXa5r4dXXHnn+LyoQTbQqLVOnn1IJmY0XOHMJc6h08nMxEaycnr4nZBcsjwemQKXU8bfWHu/Y3Sv2h4poct14P8iL9nsRzo2XqWMkeCuRtLB+B9tJiyEvSHPbrBr94yiR23QViuQNbFtsw8fVTeELsgiieyuYrdVAmTgMW8X5CDAugmAHiF1mxIYnYJg3asvFYGYJuJgI0qoXyZfsINQw/1JUUyCfYAVJdBF8iqaS0Wvp9siT7be031OhIPBVbDtSVqXLjQeOdItViFhPNclMIFV8FH80rRfyRhk/yEbvzYmWueF2fWCf3qa3baJRduwg6uikH58YTWpbXS8OGTv6jf8DsBnsUy44lBPLBdC4H36tAJ6R2aNuo5YrtYSOmPQd+DA+z5klPKcOzelo+sjg2SVRM/pYkXR+AlQjeoJOKoqfIxfKzwznUK1jALxKmI0UgpOduw90nWCnCxMdxUGFxZi92vq4GoBN+a34Ssl2Px4k1FTW+NgWHpn4yvfYT2lQd9Ris1G44pt/pkzF0lrRtiTw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
